version: '3'

services:
  nginx:
    build: 
      context: ./nginx
    image: cljos/nginx-node
    container_name: nginx-node
    hostname: nginx-node
    restart: always
    networks:
      - desafio_network
    ports: 
      - "8080:80"
    depends_on:
      - app
  app:
    build:
      context: ./node
    container_name: nodesvr
    hostname: nodesvr
    networks:
      - desafio_network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db-mysql
    restart: always
    tty: true
    volumes:
      - ./scripts/table.sql:/docker-entrypoint-initdb.d/1.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=desafiodb
      - MYSQL_ROOT_PASSWORD=desafio
    networks:
      - desafio_network

networks:
  desafio_network:
    driver: bridge